import {WikiLevelFactory} from "./WikiLevelFactory.js";
import {QuestInput} from "../quest/QuestInput.js";
import {Quest} from "../quest/Quest.js";

export class WikiQuestInput extends QuestInput {
	constructor(doc, callback, difficulty) {
		super(callback, difficulty);
		this.levelFactory = new WikiLevelFactory();
		this.doc = doc;
	}

	getLevelFactory() {
		return this.levelFactory;
	}

	updateDoc(doc) {
		this.doc = doc;
	}
}

export class WikiQuestFactory {
	/**
	 * doc is the document generated by the WikiLevelFactory request.
	 * callback is the function to call after the quest has been generated.
	 * difficulty should represent how many stairs it will take to get
	 * 		from the current page to the end of the quest.
	 */ 
	static generate(doc, callback, difficulty = 1) {
		const questInput = new WikiQuestInput(doc, callback, difficulty);
		(new WikiQuestFactory()).getQuest(questInput);
	}

	/**
	 * From the current page, how many steps do I need to find 
	 */ 
	getQuest(questInput) {
		const path = this.getRandomPath(questInput.doc);
		
		questInput.addPath(path);
		if (questInput.difficulty <= 0)  {
			questInput.callback(new Quest(questInput.path));
			return;
		}

		questInput.getLevelFactory().fetch(
			path.link,
			(doc) => {
				if (!doc) {
					console.error("DOC is null for " + path.link);
					questInput.callback(questInput);
					return;
				}
				questInput.updateDoc(doc);
				this.getQuest(questInput);
			},
			(error) => {
				console.error(error);
				questInput.callback(questInput);
			}
		);
	}

	getRandomPath(doc) {
		const randomSection = this.getRandomElement(doc, "sections");
		const randomLink = this.getRandomElement(randomSection, "links");
		if (!randomLink) {
			return this.getRandomPath(doc);
		}

		return {
			level: doc.title(),
			room: randomSection.title().length > 1 ?
				randomSection.title() : doc.title(),
			exit: randomLink.page()
		};
	}

	getRandomElement(doc, funcName) {
		return doc[funcName]()[
			Math.floor(Math.random() * doc[funcName]().length)
		];
	}
}