import {WikiLevelFactory} from "./WikiLevelFactory.js";
import {QuestInput} from "../quest/QuestInput.js";
import {Quest} from "../quest/Quest.js";
import {QuestStorage} from "../quest/QuestStorage.js";

export class WikiQuestInput extends QuestInput {
	constructor(doc, callback, difficulty) {
		super(callback, difficulty);
		this.levelFactory = new WikiLevelFactory();
		this.doc = doc;
	}

	getLevelFactory() {
		return this.levelFactory;
	}

	updateDoc(doc) {
		this.doc = doc;
	}
}

export class WikiQuestFactory {
	/**
	 * doc is the document generated by the WikiLevelFactory request.
	 * callback is the function to call after the quest has been generated.
	 */
	static findQuest(doc) {
		const factory = new WikiQuestFactory();
		return factory.acceptedQuest(doc.title());
	}

	acceptedQuest(title) {
		const storage = new QuestStorage();
		const accepted = storage.get("accepted") || [];
		for (let i = 0; i < accepted.length; i ++) {
			const keys = Object.keys(accepted[i])
			for (let keyI = 0; keyI < keys.length; keyI ++) {
				let j = keys[keyI];
				if (
					this.doesTitleMatch(title, accepted[i][j])
				) {
					return new Quest(accepted[i]);
				}
			}
		}
	}

	doesTitleMatch(title, pathStep) {
		return title.toUpperCase() == pathStep.level.toUpperCase()
			|| title.toUpperCase() == pathStep.exit.toUpperCase();
	}


	/**
	 * doc is the document generated by the WikiLevelFactory request.
	 * callback is the function to call after the quest has been generated.
	 * difficulty should represent how many stairs it will take to get
	 * 		from the current page to the end of the quest.
	 */ 
	static generate(doc, callback, difficulty = 1) {
		const questInput = new WikiQuestInput(doc, callback, difficulty);
		console.log("quest input", questInput, new WikiQuestFactory());
		(new WikiQuestFactory()).getQuest(questInput);
	}

	/**
	 * From the current page, how many steps do I need to find 
	 */ 
	getQuest(questInput) {
		const path = this.getRandomPath(questInput.doc);
		
		questInput.addPath(path);
		if (questInput.difficulty <= 0)  {
			questInput.callback(new Quest(questInput.path));
			return;
		}

		questInput.getLevelFactory().fetch(
			path.exit,
			(doc) => {
				if (!doc) {
					console.error("DOC is null for " + path.exit);
					questInput.callback(new Quest(questInput.path));
					return;
				}
				questInput.updateDoc(doc);
				this.getQuest(questInput);
			},
			(error) => {
				console.error(error);
				questInput.callback(new Quest(questInput.path));
			}
		);
	}

	getRandomPath(doc) {
		const randomSection = this.getRandomElement(doc, "sections");
		const randomLink = this.getRandomElement(randomSection, "links");
		if (!randomLink || !randomLink.page()) {
			return this.getRandomPath(doc);
		}

		return {
			level: doc.title(),
			room: randomSection.title().length >= 1 ?
				randomSection.title() : doc.title(),
			exit: randomLink.page()
		};
	}

	getRandomElement(doc, funcName) {
		return doc[funcName]()[
			Math.floor(Math.random() * doc[funcName]().length)
		];
	}
}