export const NORTH_SINGLE = "NORTH_SINGLE";
export const NORTH_RIGHT = "NORTH_RIGHT";
export const NORTH = "NORTH";
export const NORTH_LEFT = "NORTH_LEFT";
export const NORTH_WEST_CORNER = "NORTH_WEST_CORNER";
export const NORTH_WEST = "NORTH_WEST";
export const WEST_TOP = "WEST_TOP";
export const WEST = "WEST";
export const WEST_BOTTOM = "WEST_BOTTOM";
export const SOUTH_WEST = "SOUTH_WEST";
export const SOUTH_WEST_CORNER = "SOUTH_WEST_CORNER";
export const SOUTH_LEFT = "SOUTH_LEFT";
export const SOUTH = "SOUTH";
export const SOUTH_RIGHT = "SOUTH_RIGHT";
export const SOUTH_EAST = "SOUTH_EAST";
export const SOUTH_EAST_CORNER = "SOUTH_EAST_CORNER";
export const EAST_BOTTOM = "EAST_BOTTOM";
export const EAST = "EAST";
export const EAST_TOP = "EAST_TOP";
export const NORTH_EAST = "NORTH_EAST";
export const NORTH_EAST_CORNER = "NORTH_EAST_CORNER";

export const CENTER = "CENTER";
export const CENTER_NORTH_WEST_CORNER = "CENTER_NORTH_WEST_CORNER";
export const CENTER_NORTH = "CENTER_NORTH";
export const CENTER_NORTH_WEST = "CENTER_NORTH_WEST";
export const CENTER_WEST = "CENTER_WEST";
export const CENTER_NORTH_EAST = "CENTER_NORTH_EAST";

export const ORIENTATIONS = [
	NORTH_SINGLE,
	NORTH_RIGHT,
	NORTH,
	NORTH_LEFT,
	NORTH_WEST_CORNER,
	NORTH_WEST,
	WEST_TOP,
	WEST,
	WEST_BOTTOM,
	SOUTH_WEST,
	SOUTH_WEST_CORNER,
	SOUTH_LEFT,
	SOUTH,
	SOUTH_RIGHT,
	SOUTH_EAST,
	SOUTH_EAST_CORNER,
	EAST_BOTTOM,
	EAST,
	EAST_TOP,
	NORTH_EAST,
	NORTH_EAST_CORNER,
	CENTER,
	CENTER_NORTH_WEST_CORNER,
	CENTER_NORTH_WEST,
	CENTER_WEST,
	CENTER_NORTH,
	CENTER_NORTH_EAST,
];